name: example
description: For testing the flutter_theme_package

version: 1.0.0+3

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  auto_size_text: ^2.1.0
  cupertino_icons: ^0.1.3
  notifier: ^1.0.2
  shared_preferences: ^0.5.6+2
  flutter_mode_color:
    git:
      url: https://github.com/SilversphereInc/flutter_mode_color.git
  flutter_theme_package:
    path: ../
  flutter_tracers:
    git:
      url: https://github.com/SilversphereInc/flutter_tracers.git

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
  assets:
    - images/
