name: flutter_theme_package
description: A Flutter package to handle light/dark mode themes
version: 0.0.3+5
homepage: https://www.silversphere.com

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  # have text auto size to fill/shrink space
  auto_size_text: ^2.1.0
  # Download, cache and show images
  cached_network_image: ^2.0.0
  cupertino_icons: ^0.1.3
  flutter_tracers:
    git:
      url: https://github.com/GitHubStuff/flutter_tracers.git
  http: ^0.12.0+4
  #Provides internationalization and localization facilities, including message translation, plurals
  # and genders, date/number formatting and parsing, and bidirectional text.
  intl: ^0.16.1
  #notifier: ^1.0.2
  shared_preferences: ^0.5.6+1
  transparent_image: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
  assets:
    - images/
