name: flutter_theme_package
description: A Flutter package to handle light/dark mode themes
version: 0.1.2+1
homepage: https://www.silversphere.com

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  auto_size_text: ^2.1.0
  cached_network_image: ^2.0.0
  cupertino_icons: ^0.1.3
  flutter_mode_color:
    git:
      url: https://github.com/SilversphereInc/flutter_mode_color.git
  flutter_tracers:
    git:
      url: https://github.com/SilversphereInc/flutter_tracers.git
  http: ^0.12.0+4
  intl: ^0.16.1
  shared_preferences: ^0.5.6+2
  transparent_image: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
  assets:
    - images/
